DATA SEGMENT
    X DB 3
    Y DB 2
    Z DB ?
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START : MOV AX, DATA ;DATA SEGMENT INITIALIZATION
    MOV DS, AX
    MOV AL, X ; READ 2 NUMBERS
    MOV BL, Y
    ADD AL, BL ; COMPUTE SUM
    SHR AL, 1 ;COMPUT SUM/2
    MOV Z, AL ; OUTPUT RESULT
    MOV AH, 4CH
    INT 21H
    CODE ENDS
END START